### ISSUE TITLE
[Bug]: Combining Does not Show Result (Can't Craft in short)

### ISSUE THREAD

**Issue by ardissaps** [TheIllusiveC4/Bedspreads#21] opened 2022-07-05 06:14 UTC
### Minecraft Version

1.18.2

### What happened?

![image](https://user-images.githubusercontent.com/82106625/177261706-288379d7-ba5a-4e95-a0e5-df6d94325666.png)

### How do you trigger this bug?

In the Picture

### Loader

Fabric

### Loader Version

Latest

### Mod Version

Latest

### Relevant Log Outputs

https://paste.atlauncher.com/view/21e7d0fc-6964-4b9f-914b-35f5acb24e8e

**Comment by ardissaps** [comment] 2022-07-05 06:21
I found it, need to turn off the Enhanced Bed from [EBE](https://modrinth.com/mod/ebe). Would you like to use EBE baked model format as custom bed models? As it can increase performance (from what they say) when many beds in the area (it use Baked Model instead of Block Entity). Thank you, as now I have to choose between pattern or conserve power.
![image](https://user-images.githubusercontent.com/82106625/177262992-83fed73c-c4b5-4279-bf3f-a867528d7653.png)

**Comment by TheIllusiveC4** [comment] 2022-07-05 09:38
I've tested this and you actually can craft it. You can even grab it and place it down and it'll render as normal. The problem is that it doesn't render when in your inventory or in the crafting result slot (although it does exist) and I believe that's something that needs to be addressed from EBE. I suspect that they're modifying the rendering of all bed blocks instead of just vanilla beds and it's failing because this is a custom bed block.

I would suggest reporting this incompatibility to EBE and see what they say. Until then, I'll be closing this as a third-party issue. You may feel free to ask me to re-open this if the need arises.

**Closed as completed by TheIllusiveC4** 2022-07-05 09:38 UTC
Labels: type: bug, status: resolved

**Comment by ardissaps** [comment] 2022-07-05 10:33
The bed looks cool with banner, I hope they will respon, so it is only matter of inventory icon right? Can it be fixed with resource pack?

**Comment by TheIllusiveC4** [comment] 2022-07-05 11:40
Yes, I believe it's just a rendering issue in the inventory. No, I don't believe you can fix it with a resource pack.
