### ISSUE TITLE
[Bug]: SVL Modpack-Server (selfmade) crashes with Bedspread 5.1.0.4 on 1.18.1

### ISSUE THREAD

**Issue by raphipod** [TheIllusiveC4/Bedspreads#19] opened 2022-02-02 20:31 UTC
### Minecraft Version

1.18.1

### What happened?

Forge server suddenly crashes.

### How do you trigger this bug?

Self-created Forge server pack for Slightly Vanilla Flavoured (Modpack, CurseForge) suddenly crashed with error message down below.
I've run this server for days and never had this problem up until now.
To my knowledge no one on my server had used the features of your modpack before the crash.

### Loader

Forge

### Loader Version

Forge 39.0.63

### Mod Version

Bedspreads 1.18.1 - 5.1.0.4

### Relevant Log Outputs

[20:41:58] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:872) ~[server-1.18.1-20211210.034407-srg.jar%23113!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328) ~[server-1.18.1-20211210.034407-srg.jar%23113!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[server-1.18.1-20211210.034407-srg.jar%23113!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%23113!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23113!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag net.minecraft.world.level.block.entity.BlockEntity.save(net.minecraft.nbt.CompoundTag)'
	at top.theillusivec4.bedspreads.common.DecoratedBedBlockEntity.save(DecoratedBedBlockEntity.java:76) ~[bedspreads-forge-1.18-5.1.0.4.jar%2346!/:task ':jar' property 'archiveVersion']
	at top.theillusivec4.bedspreads.common.DecoratedBedBlockEntity.m_5995_(DecoratedBedBlockEntity.java:114) ~[bedspreads-forge-1.18-5.1.0.4.jar%2346!/:task ':jar' property 'archiveVersion']
	at net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket.m_195642_(ClientboundBlockEntityDataPacket.java:21) ~[server-1.18.1-20211210.034407-srg.jar%23113!/:?]
	at net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket.m_195640_(ClientboundBlockEntityDataPacket.java:25) ~[server-1.18.1-20211210.034407-srg.jar%23113!/:?]
	at top.theillusivec4.bedspreads.common.DecoratedBedBlockEntity.m_183216_(DecoratedBedBlockEntity.java:108) ~[bedspreads-forge-1.18-5.1.0.4.jar%2346!/:task ':jar' property 'archiveVersion']
	at top.theillusivec4.bedspreads.common.DecoratedBedBlockEntity.m_183216_(DecoratedBedBlockEntity.java:39) ~[bedspreads-forge-1.18-5.1.0.4.jar%2346!/:task ':jar' property 'archiveVersion']
	at net.minecraft.server.level.ChunkHolder.m_140029_(ChunkHolder.java:228) ~[server-1.18.1-20211210.034407-srg.jar%23113!/:?]
	at net.minecraft.server.level.ChunkHolder.m_140032_(ChunkHolder.java:220) ~[server-1.18.1-20211210.034407-srg.jar%23113!/:?]
	at net.minecraft.server.level.ChunkHolder.m_140076_(ChunkHolder.java:206) ~[server-1.18.1-20211210.034407-srg.jar%23113!/:?]
	at net.minecraft.network.protocol.game.ClientboundSectionBlocksUpdatePacket.m_132992_(ClientboundSectionBlocksUpdatePacket.java:72) ~[server-1.18.1-20211210.034407-srg.jar%23113!/:?]
	at net.minecraft.server.level.ChunkHolder.m_140054_(ChunkHolder.java:205) ~[server-1.18.1-20211210.034407-srg.jar%23113!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_184021_(ServerChunkCache.java:371) ~[server-1.18.1-20211210.034407-srg.jar%23113!/:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:370) ~[server-1.18.1-20211210.034407-srg.jar%23113!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_142483_(ServerChunkCache.java:311) ~[server-1.18.1-20211210.034407-srg.jar%23113!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:278) ~[server-1.18.1-20211210.034407-srg.jar%23113!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[server-1.18.1-20211210.034407-srg.jar%23113!/:?]
	... 5 more

**Comment by TheIllusiveC4** [comment] 2022-02-03 00:29
Duplicate of https://github.com/TheIllusiveC4/Bedspreads/issues/18
Update Bedspreads to the latest version.

**Closed as completed by TheIllusiveC4** 2022-02-03 00:29 UTC
Labels: type: bug, status: duplicate
